"""detect server default

Revision ID: 85d241f06838
Revises: 874ed61bf8d0
Create Date: 2018-02-12 02:15:16.662747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85d241f06838'
down_revision = '874ed61bf8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('statement_timestamp()'),
               existing_nullable=False)
    op.alter_column('accounts', 'id',
               existing_type=postgresql.UUID(),
               server_default=sa.text('uuid_generate_v4()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'id',
               existing_type=postgresql.UUID(),
               server_default=None)
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###
