"""add activated_at to accounts

Revision ID: 328f7bdc03dd
Revises: 85d241f06838
Create Date: 2018-03-19 18:09:13.598270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328f7bdc03dd'
down_revision = '85d241f06838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('activated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'activated_at')
    # ### end Alembic commands ###
